server:
  port: 8080

mybatis:
  type-aliases-package: com.learn.common.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

spring:
  application:
    name: free-im
  datasource:
    druid:
      url: jdbc:mysql://47.104.252.148:3306/free_im_db?useUnicode=true&character_set_server=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: freeim
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #是否缓存preparedStatement
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置扩展插件
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
snowflake:
  workId: 1
  datacenterId: 1
